djangoProject/urls.py

from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('planner.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='car_list/main.html'), name='logout'),
]

planner/urls.py

from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('add_task/', views.add_task, name='add_task'),
    path('delete/<int:task_id>/', views.delete_task, name='delete'),
    path('edit_task/<int:task_id>/', views.edit_task, name='edit_task'),
    path('add_label/', views.add_label, name='add_label'),
    path('delete_label/<int:label_id>/', views.delete_label, name='delete_label'),

]

planner/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from colorfield.fields import ColorField
from django.contrib.auth.models import User


class Label(models.Model):
    name = models.CharField(max_length=255)
    color = models.CharField(max_length=7, default="#000000")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    is_project = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    finish = models.DateField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now, blank=True)
    labels = models.ManyToManyField(Label, related_name='tasks', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Task(models.Model):
    task = models.CharField('task', max_length=50)
    description = models.TextField('description', blank=True)
    checkbox = models.BooleanField('', default=False, null=True)
    finish = models.DateField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    priority = models.IntegerField(blank=True, null=False, default=1, validators=[MinValueValidator(1), MaxValueValidator(4)])
    project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True, null=True)
    labels = models.ManyToManyField(Label, related_name='projects', blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def add_to_project(self, project):
        self.project = project
        self.save()

    def save(self, *args, **kwargs):
        # Проверяем, является ли выбранная категория проектом
        if self.category and self.category.is_project:
            # Если выбранная категория является проектом, сохраняем только проект
            project = Project.objects.create(name=self.task, description=self.description, finish=self.finish)
            project.save()
            self.project = project
        else:
            # Если выбранная категория не является проектом, сохраняем задачу и проект (если он задан)
            super().save(*args, **kwargs)
            if self.project:
                self.project.save()

    def __str__(self):
        return self.task

planner/forms.py
from .models import Task, Label
from django.forms import ModelForm, TextInput, Textarea, ModelChoiceField
from django import forms


class TaskForm(ModelForm):

    class Meta:
        model = Task
        fields = '__all__'
        widgets = {
            "task": TextInput(attrs={'class': 'addtask_name_input',
                                     'id': 'id_task',
                                    'placeholder': 'Название задачи',
                                    'autocomplete':'off'}),
            "description": Textarea(attrs={'class': 'addtask_description_input',
                                     'placeholder': 'Описание задачи',
                                     'style': 'width: 100%;'}),
            "checkbox": False,
            "finish": forms.DateInput(attrs={"id": "airdatepicker", "class": 'addtask_date_input',
                                             'autocomplete': 'off', 'placeholder': 'Date'}),
        }


class EditTaskForm(ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        widgets = {
            "task": TextInput(attrs={'class': 'addtask_name_input',
                                    'placeholder': 'Название задачи',
                                    'autocomplete':'off'}),
            "description": Textarea(attrs={'class': 'addtask_description_input',
                                     'placeholder': 'Описание задачи'}),
            "finish": forms.DateInput(attrs={"id": "airdatepicker-2", "class": 'addtask_date_input',
                                             'autocomplete': 'off', 'placeholder': 'Date'}),
        }

planner/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from .models import Task, Category, Label
from .forms import TaskForm, EditTaskForm
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse



def index(request):
    tasks = Task.objects.filter(user=request.user)
    form = TaskForm(initial={'checkbox': False})
    edit = EditTaskForm()
    cat = Category.objects.all()
    labels = Label.objects.filter(user=request.user)

    category_id = request.GET.get('category')

    if category_id and category_id != "":
        # Если передан параметр категории и он не пустой, фильтруем задачи по этой категории
        tasks = tasks.filter(category_id=category_id)
    else:
        # Если категория не выбрана, включаем в результаты задачи без категории
        tasks = tasks.filter(category__isnull=True)

    return render(request, 'planner/index.html',
                  {'tasks': tasks, 'form': form, 'edit': edit, 'cat': cat, 'labels': labels})


@login_required
def add_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            checkbox = request.POST.get('checkbox') == 'True'
            task.checkbox = checkbox
            task.save()
            labels: object = request.POST.getlist('labels')
            task.labels.set(labels)
            return JsonResponse({'success': True})
        else:
            errors = form.errors.as_json()
            print(errors)  # Отладочное сообщение
            return JsonResponse({'success': False, 'errors': errors})
    else:
        form = TaskForm(initial={'checkbox': False})
    return render(request, 'planner/add_task.html', {'form': form})


def delete(request, task_id):
    todo = Task.objects.get(id=task_id)
    todo.delete()

    return redirect('index')

def delete_task(request, task_id):
    task = get_object_or_404(Task, id=task_id)

    category_done = Category.objects.get(name='Выполнено')
    if task.category != category_done:
        # Присвоить категорию "Выполнено"
        task.category = category_done
        task.save()
    else:
        task.delete()

    return HttpResponseRedirect(reverse('index'))

def edit_task(request, task_id):
    if request.method == 'POST':
        task = get_object_or_404(Task, id=task_id)
        task_form = EditTaskForm(request.POST, instance=task)
        if task_form.is_valid():
            task_form.save()
            labels: object = request.POST.getlist('labels-edit')
            task.labels.set(labels)
            return HttpResponse(status=200)
        else:
            errors = task_form.errors.as_json()
            return HttpResponseBadRequest(errors)
    else:
        # Handle GET requests
        pass


@csrf_exempt
@login_required
def add_label(request):
    if request.method == 'POST' and request.headers.get('x-requested-with') == 'XMLHttpRequest':
        name = request.POST.get('name')
        color = request.POST.get('color')
        if name:
            label = Label(name=name, color=color)
            label.user = request.user
            label.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'error': 'Name is required'})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid method or request'})

@login_required
def delete_label(request, label_id):
    try:
        label = Label.objects.get(id=label_id, user=request.user)
        label.delete()
        return JsonResponse({'success': True})
    except Label.DoesNotExist:
        return JsonResponse({'success': False, 'error': 'Метка не найдена'})


planner/templates/planner/add_form.html
<div class="slide-add-form">Добавить задачу</div>
<form class="form-task-add" method="post" id="task-add">
    {% csrf_token %}
    {{ form.task }}
    <div class="addtask_options">
        {{ form.description }}
    </div>
    <div class="addtask_buttons_field">
      <div class="addtask_options_date">
        {{ form.finish }}
      </div>
      <div class="addtask_options_category">
          <select name="category" id="id_category" class="select2-category" style="margin: 8px">
              <option value=""></option>
              {% for c in cat %}
                  <option value="{{ c.pk }}">{{ c.name }}</option>
              {% endfor %}
          </select>
      </div>
    <div class="addtask_options_category">
        <select name="labels" id="id_labels" multiple="multiple" class="select2-add" style="width: 50%; background-color: #4a4a4a;">
            {% for l in labels %}
                <div class="choise_label" style="display: flex; flex-direction: row;">
                    <div class="label_color" style="background-color: {{ l.color }}"></div>
                    <option value="{{ l.pk }}">{{ l.name }}</option>
                </div>
            {% endfor %}
        </select>
    </div>
        <button class="addtask_cancel_btn" type="reset">X</button>
      <button class="addtask_submit_btn" type="submit">+</button>
    </div>
</form>

planner/templates/planner/edit_form.html
<form id="edit-task-form" class="edittask_section" method="post" action="{% url 'edit_task' task_id=0 %}">
  {% csrf_token %}
  <input type="hidden" name="task_id" value="">
  {{ edit.task }}
  <div class="addtask_options">
    {{ edit.description }}
  </div>
  <div class="edit-task-options-first">
      {{ edit.finish }}
      <div class="addtask_options_category">
          <select name="category" id="id_category" class="select2-category-edit" style="margin: 8px">
              <option value=""></option>
              {% for c in cat %}
                  <option value="{{ c.pk }}">{{ c.name }}</option>
              {% endfor %}
          </select>
      </div>
  </div>
    <div class="edit-task-labels-field">
    <select name="labels" id="id_labels" multiple="multiple" class="select2-edit" style="width: 50%; background-color: #4a4a4a;">
            {% for l in labels %}
                <div class="choise_label" style="display: flex; flex-direction: row;">
                    <div class="label_color" style="background-color: {{ l.color }}"></div>
                    <option value="{{ l.pk }}">{{ l.name }}</option>
                </div>
            {% endfor %}
        </select>
    </div>
  <div class="addtask_buttons_field">
    <button class="addtask_submit_btn" type="submit" style="width: 50px; height: 30px;">Update</button>
  </div>
</form>

planner/templates/planner/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>to do GTD</title>

    <link rel="stylesheet" href="{% static 'planner/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'planner/css/reset.css' %}">
    <link href="{% static 'planner/airdatepicker/air-datepicker.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/spectrum-colorpicker2/dist/spectrum.min.css">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{% static 'planner/css/select2.css' %}">

</head>
<body>
    {% include 'planner/topbar.html' %}
    </div>
    <div class="app-section">
        {% include 'planner/left_menu.html' %}
        <div class="main-section">
            {% include 'planner/add_form.html' %}
            {% include 'planner/task_list.html' %}
        </div>
        {% include 'planner/edit_form.html' %}

    </div>
<script src="{% static 'planner/airdatepicker/air-datepicker.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
   $(document).ready(function() {
      $('#task-add').submit(function(event) {
        event.preventDefault();

        // Получаем идентификатор текущего пользователя
        var userId = '{{ request.user.id }}';

        // Собираем данные формы
        var formData = $(this).serialize();
        formData += '&user=' + userId;

        $.ajax({
          type: 'POST',
          url: '{% url "add_task" %}',
          data: formData,
          success: function(response) {
            if (response.success) {
              location.reload();
            } else {
              if (response.errors && response.errors.__all__) {
                var errors = response.errors.__all__;
                alert('Ошибка: ' + errors[0]);
              } else {
                alert('Произошла ошибка при обработке запроса.');
              }
            }
          }
        });
      });
    });
    $(document).ready(function() {
      $('#add-label-form').submit(function(event) {
        event.preventDefault();
        var name = $('.label_name_input').val();
        var color=$('.label_color_input').val();
        $.ajax({
          type: 'POST',
          url: '{% url "add_label" %}',
          data: {
            'name': name,
            'color': color,
            'csrfmiddlewaretoken': '{{ csrf_token }}'
          },
          success: function(response) {
            if (response.success) {
              location.reload();
            } else {
              var errors = JSON.parse(response.errors);
              alert('Ошибка: ' + errors.__all__[0]);
            }
          }
        });
      });
    });

    $(document).ready(function() {
      $('.delete-label-btn').click(function() {
        var labelId = $(this).data('label-id');
        var deleteUrl = '/delete_label/' + labelId + '/';

        $.ajax({
          type: 'POST',
          url: deleteUrl,
          data: {
            'csrfmiddlewaretoken': '{{ csrf_token }}'
          },
          success: function(response) {
            if (response.success) {
              location.reload();
            } else {
              alert('Ошибка удаления метки: ' + response.error);
            }
          }
        });
      });
    });

</script>
<script src="{% static 'planner/js/redact.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/spectrum-colorpicker2/dist/spectrum.min.js"></script>
<script>
  $('#color-picker').spectrum({
  type: "color",
  togglePaletteOnly: true,
});
</script>
<script src="{% static 'planner/js/select2.js' %}"></script>
<script>
$(document).ready(function() {
    $('.select2-add').select2({
        placeholder: "Labels",
    });
    $('.select2-category').select2({
        minimumResultsForSearch: Infinity,
        placeholder: "Category",
    });
    $('.select2-category-edit').select2({
        minimumResultsForSearch: Infinity,
        placeholder: "Category",
    });

    let prevHeight = $('.select2-selection__rendered').height();
    $('.select2-selection__rendered').on('DOMSubtreeModified', function () {
        let height = $(this).height();
        let diff = height - prevHeight;
        console.log(diff + prevHeight);
        $('.form-task-add').css('height', '+=' + diff);
        prevHeight = height;

    });
    function adjustAddFormHeight() {
        let addFormHeight = $('.form-task-add').outerHeight();
        let taskListHeight = $('.task_list_section').outerHeight();
        $('.task_list_section').css('max-height', `calc(100% - ${addFormHeight}px)`);
    }
    $(document).ready(function() {
        // Вызываем функцию при загрузке страницы
        adjustAddFormHeight();
        // И при каждом изменении содержимого формы добавления
        $('.form-task-add').on('DOMSubtreeModified', function() {
            adjustAddFormHeight();
        });
    });
});
</script>
</body>
</html>

planner/templates/planner/left_menu.html
<div class="left_menu_section">
            <div class="section_title">Категории</div>
            <div class="section_list">
                <a class="section_item" href="{% url 'index' %}">Корзина</a>
                {% for category in cat %}
                  <a class="section_item" href="{% url 'index' %}?category={{ category.id }}">{{ category.name }}</a>
                {% endfor %}
            </div>
            <div class="labels_section">
              <div class="labels_field">
                <div class="section_title">Метки</div>
                <div class="add_label_btn">+</div>
              </div>
              <form method="post" id="add-label-form">
                  {% csrf_token %}
                <div class="add_label_form_field">
                  <div class="label_inputs">
                    <input id="color-picker" value='#276cb8' placeholder="color" class="label_color_input"/>
                    <input type="text" class="label_name_input" placeholder="label name1" name="name" autocomplete="off">
                  </div>
                  <div class="add_label_btns_field">
                    <button type="submit" class="add_label_form_btn">new label</button>
                    <button type="reset" class="cancel_label_form_btn">cancel</button>
                  </div>
                </div>
              </form>
                {% for l in labels %}
                    <div class="section_item" style="display: flex; flex-direction: row">
                        <div class="label_color" style="background-color: {{ l.color }}"></div>
                        <span>{{ l.name }}</span>
                        <button class="delete-label-btn" data-label-id="{{ l.pk }}">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                              <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                            </svg>
                        </button>
                    </div>
                {% endfor %}
            </div>
</div>

planner/templates/planner/task_list.html
<div class="task_list_section">
    {% for t in tasks %}
        <div class="task" data-task-id="{{ t.id }}">
            <a class="task_checkbox" href="{% url 'delete' t.id %}"></a>
            <div class="task_info">
                <div class="task_name">{{ t.task }}</div>
                <div class="task_description">{{ t.description }}</div>
            </div>
            {% for l in t.labels.all %}
                <div class="task_labels" lab_pk = "{{ l.pk }}" style="color: {{ l.color }}">{{ l.name|default_if_none:"-" }}</div>
            {% endfor %}
            <div class="task_date" date="{{ t.finish|date:'d.m.Y' }}">{{ t.finish|default_if_none:"-"  }}</div>
            <div class="task_cat">{{ t.category|default_if_none:"-" }}</div>
        </div>
    {% endfor %}
</div>

planner/templates/planner/topbar.html
<div class="bg-neutral-900 font-sans w-full m-0">
	<div class="bg-neutral-900 shadow bg-opacity-0">
    <div class="container mx-auto px-4">
      <div class="flex items-center justify-between py-2">
        <div>
          <div class="text-2xl font-bold text-white text-shadow-lg">GTD</div>
        </div>
        <div class="hidden sm:flex sm:items-center">
        </div>

        <div class="hidden sm:flex sm:items-center">
          {% if user.is_authenticated %}
              <h1 class="text-gray-500 text-xs font-semibold hover:text-red-600 mr-4"> {{ user }}</h1>
              <a href="{% url 'logout' %}" class="text-gray-500 text-xs font-semibold hover:text-red-600 mr-4">Выйти</a>
          {% else %}
              <a href="{% url 'login' %}" class="text-gray-500 text-xs font-semibold hover:text-red-600 mr-4">Sign in</a>
              <a href="{% url 'logout' %}" class="text-gray-500 text-xs font-semibold border px-2 py-2 rounded-lg hover:text-red-600 hover:border-red-600">Sign up</a>
          {% endif %}
        </div>
      </div>

    </div>
  </div>
</div>